Repository Mr-3rd/MCTC_ITEC2905_fall2023_proj3_team03_Justin_Amy_Peng, pull requests merged in 2023-10, with the labels that each got.

#16 YouTube Embed Links:
  .gitignore
  Tests/test_video_api
  apis/video_api.py
Labels: enhancement

#10 Flickr Photo API Return:
  .gitignore
  Tests/test_photo_api.py
  apis/photo_api.py
Labels: enhancement

#15 get yelp shops:
  Tests/test_shops._api.py
  apis/shops_api.py
Labels: enhancement

#11 Car recall api
  Tests/test_get_car_recall.py
  apis/car_recall_api.py
Labels: enhancement

#23 Git Flask Setup:
  app.py
Labels: Parallel Development

#24 Created car_input.html
  templates/car_input.html
Labels: enhancement

#27 Flick & You Comments and Doc String:
  apis/photo_api.py
  apis/video_api.py
Labels: documentation

#29 Create the base html:
  templates/base.html
  templates/car_input.html
Labels: enhancement

#32 pulled latest changes, added reset button to car_input.html
  templates/car_input.html
Labels: enhancement

#39 Created static folder. Add cars_style.css.
  static/car.jpg
  static/cars_style.css
Labels: enhancement

#40 Added bookstrap, google fonts and stylesheet.
  templates/base.html
Labels: enhancement

#38 Recall Results:
  apis/__init__.py
  apis/car_recall_api.py
  apis/photo_api.py
  apis/shops_api.py
  apis/video_api.py
  app.py
  templates/car_recalls.html
  templates/error.html
Labels: bug, enhancement

#43 Updated requirements.txt
  requirements.txt
  requitements.txt
Labels: documentation

#44 Update ReadME.md. Including Description on the functionality of our w…
  README.md
Labels: documentation

#48 Modular error
  apis/car_recall_api.py
  apis/photo_api.py
  apis/shops_api.py
  apis/video_api.py
  app.py
  static/cars_style.css
  templates/base.html
  templates/car_input.html
  templates/car_recalls.html
Labels: bug, documentation, enhancement

#52 Bookmark PeeWee:
  Tests/test_video_api.py
  Top_recall_bookmarks.sqlite
  app.py
  database/recall.py
  templates/base.html
  templates/book_marked.html
  templates/bookmarks.html
  templates/car_recalls.html
Labels: enhancement, help wanted

#58 Update requirements.txt
  requirements.txt
Labels: documentation, enhancement

#60 Update Wording:
  static/cars_style.css
  templates/car_input.html
  templates/car_recalls.html
Labels: enhancement

#61 Unit Testing: video and phot apis
  .gitignore
  Tests/test_photo_api.py
  Tests/test_video_api
  Tests/test_video_api.py
Labels: bug
